### ISSUE TITLE
Issue while publishing WebReact

### ISSUE THREAD

**Issue by msaqib143** [OfficeDev/ProposalManager#29]
when Powershell is trying to execute  dotnet publish ..\WebReact -c Release . Its giving me error.

WebReact -> C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\WebReact\bin\Release\netcoreapp2.2\WebReact.dll
npm install
audited 923295 packages in 22.338s

59 packages are looking for funding
  run `npm fund` for details

found 15709 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
npm run build

> WebReact@0.1.0 build C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\WebReact\ClientApp
> react-scripts build

Creating an optimized production build...
Failed to compile.

./src/components-teams/general/Opportunity/NewOpportunityDocuments.js
EXEC(0,0): Error : 'DayPickerStrings' is not exported from '../../../common'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! WebReact@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the WebReact@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SheikhSaqib\AppData\Roaming\npm-cache\_logs\2020-05-12T18_14_46_865Z-debug.log

npm ERR!     C:\Users\SheikhSaqib\AppData\Roaming\npm-cache\_logs\2020-05-12T18_14_46_865Z-debug.log

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v14.2.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle WebReact@0.1.0~prebuild: WebReact@0.1.0
6 info lifecycle WebReact@0.1.0~build: WebReact@0.1.0
7 verbose lifecycle WebReact@0.1.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle WebReact@0.1.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\WebReact\ClientApp\node_modules\.bin;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\dotnet\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\maven362\bin\;C:\Program Files\Java\jdk-13\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\SheikhSaqib\AppData\Local\Microsoft\WindowsApps;;C:\Users\SheikhSaqib\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\SheikhSaqib\AppData\Roaming\npm;C:\Users\SheikhSaqib\.dotnet\tools;C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\packages\Microsoft.CodeAnalysis.VersionCheckAnalyzer.2.9.2\tools;C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\packages\Microsoft.CodeQuality.Analyzers.2.9.2\tools;C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\packages\Microsoft.NetCore.Analyzers.2.9.2\tools;C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\packages\Microsoft.NetFramework.Analyzers.2.9.2\tools;C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\packages\Microsoft.CodeAnalysis.FxCopAnalyzers.2.9.2\tools;C:\Users\SheikhSaqib\.nuget\packages\microsoft.netframework.analyzers\2.9.2\tools;C:\Users\SheikhSaqib\.nuget\packages\microsoft.netcore.analyzers\2.9.2\tools;C:\Users\SheikhSaqib\.nuget\packages\microsoft.entityframeworkcore.tools\2.2.4\tools;C:\Users\SheikhSaqib\.nuget\packages\microsoft.codequality.analyzers\2.9.2\tools;C:\Users\SheikhSaqib\.nuget\packages\microsoft.codeanalysis.versioncheckanalyzer\2.9.2\tools;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.codeanalysis.analyzers\1.1.0\tools;C:\Users\SheikhSaqib\.nuget\packages\microsoft.codeanalysis.fxcopanalyzers\2.9.2\tools;C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.aspnetcore.razor.design\2.2.0\tools
9 verbose lifecycle WebReact@0.1.0~build: CWD: C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\WebReact\ClientApp
10 silly lifecycle WebReact@0.1.0~build: Args: [ '/d /s /c', 'react-scripts build' ]
11 silly lifecycle WebReact@0.1.0~build: Returned: code: 1  signal: null
12 info lifecycle WebReact@0.1.0~build: Failed to exec build script
13 verbose stack Error: WebReact@0.1.0 build: `react-scripts build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid WebReact@0.1.0
15 verbose cwd C:\Users\SheikhSaqib\Desktop\proposalManager\ProposalManager-master\WebReact\ClientApp
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v14.2.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error WebReact@0.1.0 build: `react-scripts build`
22 error Exit status 1
23 error Failed at the WebReact@0.1.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by sushobhankundu** [comment]
I am also receiving the same error while performing Manual Deployment

'DayPickerStrings' is not exported from '../../../common'

Can anyone please tell if same issue is faced by them and how to resolve?

**Comment by msaqib143** [comment]
as a workaround , i put copy of common.js file in every folder and sub folder inside WebReact\ClientApp\src .  And then i change reference from ../../../common to common.

You need to do it multiple files as this common reference is mentioned in many other files. 

It did help me to build the code but now i am facing issue on setup channel screen in Teams where its not fetching SharpointApp ID and its secret automatically.  Its show me error : List not allowed.
